---
- name: Install Docker and setup Docker Swarm on Raspberry Pi
  hosts: localhost
  become: true
  vars:
    swarm_role: "worker"  # Change this variable to "worker" for worker nodes
    manager_ip: "drogon.localdomain"  # Set the manager IP address for worker nodes
  tasks:
    - name: Install Docker using snap
      ansible.builtin.apt:
        name: docker
        state: present

    # Install via apt instead!!!
    # - name: Ensure Docker service is running
    #   service:
    #     name: snap.docker.dockerd
    #     state: started
    #     enabled: yes

    - name: Initialize Docker Swarm (Master only)
      ansible.builtin.command: docker swarm init
      when: swarm_role == "master"
      register: swarm_init
      ignore_errors: true

    - name: Get join token for worker nodes (Master only)
      command: docker swarm join-token worker -q
      when: swarm_role == "master"
      register: worker_join_token

    - name: Define worker_join_token fact (Worker only)
      set_fact:
        worker_join_token: "{{ hostvars[manager_ip].worker_join_token }}"
      when: swarm_role == "worker" and manager_ip is defined

    - name: Fetch join token from master node
      command: ssh {{ manager_ip }} "docker swarm join-token worker -q"
      register: worker_join_token
      when: swarm_role == "worker"
      # todo: need to make this a better one from the hosts.yaml
      delegate_to: localhost

    - name: Debug - Show worker join token
      debug:
        var: worker_join_token
      when: worker_join_token is defined

    - name: Join the Docker Swarm (Worker only)
      command: docker swarm join --token {{ worker_join_token.stdout }} {{ manager_ip }}:2377
      when: swarm_role == "worker" and worker_join_token is defined

    - name: Label the node (Master only)
      command: docker node update --label-add role={{ swarm_role }} $(hostname)
      when: swarm_role == "master"
      ignore_errors: true

    - name: Label the node (Worker only)
      command: docker node update --label-add role=worker $(hostname)
      when: swarm_role == "worker"
      ignore_errors: true
