services:
  # uncomment this section and comment out the mysql section to use postgres instead of mysql
  postgres:
    restart: unless-stopped
    image: postgres:14
    hostname: postgres
    volumes: 
     - semaphore-postgres:/var/lib/postgresql/data
    environment:
     POSTGRES_USER: semaphore
     POSTGRES_PASSWORD: semaphore
     POSTGRES_DB: semaphore
  semaphore:
    restart: unless-stopped
    ports:
      - 3030:3000
    image: semaphoreui/semaphore:latest
    volumes:
     - ./:/catalyst
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: postgres # for postgres, change to: postgres
      SEMAPHORE_DB_PORT: 5432 # change to 5432 for postgres
      SEMAPHORE_DB_DIALECT: postgres # for postgres, change to: postgres
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      # SEMAPHORE_PLAYBOOK_PATH: /catalyst/
      SEMAPHORE_ADMIN_PASSWORD: panda
      SEMAPHORE_ADMIN_NAME: panda
      SEMAPHORE_ADMIN_EMAIL: panda@localhost
      SEMAPHORE_ADMIN: panda
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: gs72mPntFATGJs9qK0pQ0rKtfidlexiMjYCH9gWKhTU=
      # SEMAPHORE_LDAP_ACTIVATED: 'no' # if you wish to use ldap, set to: 'yes' 
      # SEMAPHORE_LDAP_HOST: dc01.local.example.com
      # SEMAPHORE_LDAP_PORT: '636'
      # SEMAPHORE_LDAP_NEEDTLS: 'yes'
      # SEMAPHORE_LDAP_DN_BIND: 'uid=bind_user,cn=users,cn=accounts,dc=local,dc=shiftsystems,dc=net'
      # SEMAPHORE_LDAP_PASSWORD: 'ldap_bind_account_password'
      # SEMAPHORE_LDAP_DN_SEARCH: 'dc=local,dc=example,dc=com'
      # SEMAPHORE_LDAP_SEARCH_FILTER: "(\u0026(uid=%s)(memberOf=cn=ipausers,cn=groups,cn=accounts,dc=local,dc=example,dc=com))"
      TZ: UTC
    depends_on:
      - postgres # for postgres, change to: postgres
volumes:
  semaphore-postgres: # to use postgres, switch to: semaphore-postgres