[tool.poetry]
name = "machines"
version = "0.1.0"
description = ""
readme = "README.md"
authors = ["TheBranchDriftCatalyst <djdanielsh@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12,<4.0.0"
ansible = ">=11.5.0,<12.0.0"
ansible-core = ">=2.18.5,<3.0.0"
ansible-dev-tools = ">=25.4.1,<26.0.0"
ansible-lint = ">=25.4.0,<26.0.0"
molecule = { version = ">=25.4.0,<26.0.0", extras = ["docker","lint"] }
molecule-plugins = { version = ">=23.7.0,<24.0.0", extras = ["docker"] }
antsibull-docs = "^2.16.3"
ansible-pygments = { version = "*", markers = "python_version < '4.0.0'" }