version: 3

# vars:

tasks:

  default:
    desc: Run the build and deploy tasks
    cmds:
    - echo "List of tasks:"
    - echo "  - run"

  deploy_ssh_key:
    desc: Run ansible playbook to deploy local ssh id_rsa to remotes authorized_keys
    cmds:
    - ansible-playbook -i inventory.yaml ./tasks/webservers/deploy_ssh_key.ansible.yaml -l homelab -k
  # Please create three commands here.
  # fix-link, create-link
