---
- name: Update hostname to match inventory
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Set the hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
    
    - name: Update /etc/hostname
      ansible.builtin.lineinfile:
        path: /etc/hostname
        line: "{{ inventory_hostname }}"
        create: yes

    - name: Update /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: "^127\\.0\\.1\\.1\\s"
        line: "127.0.1.1 {{ inventory_hostname }} {{ inventory_hostname }}.localdomain"
        create: yes

    - name: Restart the hostname service (if applicable)
      ansible.builtin.systemd:
        name: systemd-hostnamed
        state: restarted
        enabled: true
      when: ansible_service_mgr == "systemd"

    - name: Ensure Avahi mDNS is installed and running
      ansible.builtin.package:
        name: avahi-daemon
        state: present
      when: ansible_os_family in ["Debian", "RedHat"]

    - name: Start and enable Avahi mDNS service
      ansible.builtin.systemd:
        name: avahi-daemon
        state: started
        enabled: true
      when: ansible_service_mgr == "systemd"