homelab:
  hosts:
    truenas.localdomain:

    drogon.localdomain:

windows:
  hosts:
    gamer007.localdomain:
      ansible_user: your_username
      ansible_password: your_password
    mjolnir.localdomain:
      ansible_user: your_username
      ansible_password: your_password
    conan.localdomain:
      ansible_user: your_username
      ansible_password: your_password

all:
  children:
    swarm_nodes:
      hosts:
        # master_node:
        #   ansible_host: drogon.localdomain
        #   # ansible_user: your_user
        # rp4-[1:3]:  # Adjust the range as needed
        #   ansible_host: worker_ip{{ item }}
        #   # ansible_user: your_user

        master_node:
          ansible_host: drogon.localdomain
          ansible_user: panda
        rpi4-0:
          ansible_host: drogon.localdomain
          ansible_user: panda
        # pi[1:3]:  # Adjust the range as needed
        #   ansible_host: worker_ip{{ item }}
        #   ansible_user: panda
