homelab:
  hosts:
    truenas.localdomain:
    drogon.localdomain:

dev_machines:
  hosts:
    pandas-mbp.localdomain:

windows:
  hosts:
    gamer007.localdomain:
    mjolnir.localdomain:
    conan.localdomain:

pi_cluster:
  hosts:
    pi_master:
      ansible_host: rp0.localdomain
    rp[1:7].localdomain:
      ansible_host: rp{{ item }}.localdomain

web_servers:
  children:
    homelab:
    pi_cluster:
    dev_machines:

all:
  children:
    windows:
    pi_cluster:
    dev_machines:
    homelab:
