- name: Verify NFS mounts
  hosts: all
  tasks:
    - name: Check if NFS base directory exists
      ansible.builtin.stat:
        path: "{{ autofs_base }}"
      register: autofs_base_stat

    - name: Assert NFS base directory exists
      ansible.builtin.assert:
        that:
          - autofs_base_stat.stat.exists
        msg: "The NFS base directory {{ autofs_base }} does not exist."

    - name: Check if NFS shares are mounted
      ansible.builtin.mount:
        path: "{{ item }}"
        state: mounted
      register: mount_check
      loop:
      - "{{ nfs_exports.truenas01[0].map_name }}"
      - "{{ nfs_exports.truenas01[1].map_name }}"
      - "{{ nfs_exports.truenas02[0].map_name }}"

    - name: Assert NFS shares are mounted
      ansible.builtin.assert:
        that:
          - mount_check is defined
          - mount_check.results | map(attribute='failed') | select('equalto', True) | list | length == 0
        msg: "One or more NFS shares are not mounted."

    - name: Assert individual NFS share is mounted
      ansible.builtin.assert:
        that:
          - mount_check.results[item].rc == 0
        msg: "The NFS share {{ nfs_exports.truenas01[item].map_name }} is not mounted."
      loop: "{{ range(0, mount_check.results | length) | list }}"
