namespace: rpi_collection
name: rpi_collection
version: '1.0.0'
readme: README.md
authors:
- Your Name <your.email@example.com>
description: A collection of roles and playbooks for managing Raspberry Pi devices.
license: MIT
tags:
- raspberry_pi
- rpi4
- rpi5
- provisioning
dependencies: {}
