- name: Unmount the image
  mount:
    path: "{{ mount_point }}"
    state: unmounted

- name: Shrink filesystem
  ansible.builtin.command: "e2fsck -f {{ image_path }}"
  become: true

- name: Resize filesystem to minimum size
  ansible.builtin.command: "resize2fs -M {{ image_path }}"
  become: true

- name: Compress the image
  ansible.builtin.command: "gzip -c {{ image_path }} > {{ compressed_image }}"
  become: true
