- name: Install SOPS and SOPS dependencies
  hosts: localhost

  vars:
    key_name: "{{ ansible_facts['hostname'] }}@knowledgedump.space"
    key_comment: "SOPS ansible host"
    key_server: "pgp.mit.edu"
    sops_version: "v3.9.0"
    sops_binary: "sops-{{ sops_version }}.linux.arm64"
    sops_url: "https://github.com/getsops/sops/releases/download/{{ sops_version }}/{{ sops_binary }}"
    secrets_repo: "{{ playbook_dir | dirname }}"
  tasks:

  - name: Install dependencies
    when: ansible_os_family == "Debian"
    apt:
      name:
      - golang-go
      - curl
      - coreutils
      - gnupg
      state: present

  - name: Install GnuPG on macOS
    when: ansible_os_family == "Darwin"
    homebrew:
      name:
      - gnupg
      - golang-go
      - curl
      - coreutils
      - gnupg
      state: present

  - name: Debug sops binary
    debug:
      msg: "The sops binary to use is {{ sops_binary }}"

  - name: Download the SOPS binary
    get_url:
      url: "{{ sops_url }}"
      dest: "/tmp/{{ sops_binary }}"

  - name: Move the binary to /usr/local/bin
    command: mv /tmp/{{ sops_binary }} /usr/local/bin/sops

  - name: Make the binary executable
    file:
      path: /usr/local/bin/sops
      mode: '0755'
      state: file