# https://blog.gitguardian.com/a-comprehensive-guide-to-sops/
---
- name: Create PGP Key and Configure SOPS
  hosts: localhost
  tasks:
    - name: Install GnuPG on macOS
      when: ansible_os_family == "Darwin"
      brew:
        name: gnupg
        state: present

    - name: Install GnuPG on Linux
      when: ansible_os_family == "Debian"
      apt:
        name: gnupg
        state: present

    - name: Export key details
      set_fact:
        key_name: "Tiexin Guo"
        key_comment: "test key for sops"

    - name: Generate GPG key
      shell: |
        gpg --batch --full-generate-key <<EOF
        %no-protection
        Key-Type: 1
        Key-Length: 4096
        Subkey-Type: 1
        Subkey-Length: 4096
        Expire-Date: 0
        Name-Comment: {{ key_comment }}
        Name-Real: {{ key_name }}
        EOF
      environment:
        KEY_NAME: "{{ key_name }}"
        KEY_COMMENT: "{{ key_comment }}"
      register: gpg_key_gen

    - name: List GPG keys
      shell: gpg --list-keys
      register: gpg_list_keys

    - name: Extract GPG key fingerprint
      shell: gpg --list-secret-keys "{{ key_name }}" | grep -oP '([A-F0-9]{4} ){10}[A-F0-9]{4}'
      register: gpg_key_fingerprint

    - name: Create .sops.yaml configuration
      copy:
        dest: "{{ lookup('env', 'HOME') }}/.sops.yaml"
        content: |
          creation_rules:
            - pgp: >-
                {{ gpg_key_fingerprint.stdout.strip() }}

    - name: Print GPG key fingerprint for reference
      debug:
        msg: "GPG key fingerprint: {{ gpg_key_fingerprint.stdout.strip() }}"
