# name: Update Keys on Push to Master
# TODO: doubel check this
# Looking back at this after a while, iirc this will recreate the creation perm keys
# when a new public key is added.  Require in order for the new public key to be able to
# read old encrypted files.  Someone with permission needs to run this

# on:
#   push:
#     branches:
#       - master

# jobs:
#   update-keys:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2
#         with:
#           ref: master

#       - name: Set up SSH
#         uses: webfactory/ssh-agent@v0.5.3
#         with:
#           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#       - name: Set up Go
#         uses: actions/setup-go@v2
#         with:
#           go-version: '1.18'

#       - name: Install Task
#         run: |
#           curl -sL https://taskfile.dev/install.sh | sh

#       - name: Run Task update-keys
#         run: task update-keys

#       - name: Configure Git
#         run: |
#           git config --global user.name "github-actions[bot]"
#           git config --global user.email "github-actions[bot]@users.noreply.github.com"

#       - name: Commit changes
#         run: |
#           git add private/*
#           git commit -m "Update keys using sops"
#         continue-on-error: true

#       - name: Push changes
#         run: git push origin master
#         if: success() || failure() # Ensure the push runs even if the commit step fails (in case there are no changes to commit)
